return {
	"obsidian-nvim/obsidian.nvim",
	version = "*",
	ft = "markdown",
	dependencies = { "nvim-lua/plenary.nvim" },
	---@module 'obsidian'
	---@type obsidian.config
	opts = {
		legacy_commands = false,
		workspaces = {
			{ name = "notes", path = "~/documents/projects/notes" },
		},
		notes_subdir = "01 - Unsorted",
		new_notes_location = "notes_subdir",
		daily_notes = {
			folder = "02 - Daily",
			date_format = "%Y-%m-%d",
			workdays_only = false,
		},
		picker = { name = "snacks.pick" },
		completion = { min_chars = 2 },
		footer = { enabled = false },
		ui = { enable = false },
	},
	keys = {
		{ "<leader>oo", "<cmd>Obsidian quick_switch<cr>", desc = "Open note" },
		{ "<leader>on", "<cmd>Obsidian new<cr>", desc = "New note" },
		{ "<leader>oN", "<cmd>Obsidian new_from_template<cr>", desc = "New from template" },
		{ "<leader>os", "<cmd>Obsidian search<cr>", desc = "Search vault" },
		{ "<leader>ot", "<cmd>Obsidian tags<cr>", desc = "Tags" },
		{ "<leader>oj", "<cmd>Obsidian today<cr>", desc = "Today" },
		{ "<leader>oy", "<cmd>Obsidian yesterday<cr>", desc = "Yesterday" },
		{ "<leader>oJ", "<cmd>Obsidian dailies<cr>", desc = "Dailies" },
		{ "<leader>ob", "<cmd>Obsidian backlinks<cr>", desc = "Backlinks" },
		{ "<leader>ol", "<cmd>Obsidian links<cr>", desc = "Links in note" },
		{ "<leader>oc", "<cmd>Obsidian toc<cr>", desc = "Table of contents" },
		{ "<leader>or", "<cmd>Obsidian rename<cr>", desc = "Rename note" },
		{ "<leader>op", "<cmd>Obsidian paste_img<cr>", desc = "Paste image" },
		{ "<leader>ox", "<cmd>Obsidian toggle_checkbox<cr>", desc = "Toggle checkbox" },
		{ "<leader>oO", "<cmd>Obsidian open<cr>", desc = "Open in Obsidian app" },
		{ "<leader>ow", "<cmd>Obsidian workspace<cr>", desc = "Switch workspace" },
		{ "<leader>ol", "<cmd>Obsidian link<cr>", desc = "Link selection", mode = "v" },
		{ "<leader>oL", "<cmd>Obsidian link_new<cr>", desc = "Link to new note", mode = "v" },
		{ "<leader>oe", "<cmd>Obsidian extract_note<cr>", desc = "Extract to note", mode = "v" },
	},
}
